name: Bazel CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: namespace-profile-bazel-amd64-large

    steps:
      - uses: actions/checkout@v4

      - name: Install Bazelisk
        run: |
          curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o bazel
          chmod +x bazel
          sudo mv bazel /usr/local/bin/bazel

      - name: Verify Bazel
        run: bazel version

      - name: Build
        run: |
          cd java-tutorial
          bazel build //src/main/java/com/example/cmdline:runner
